version: "3"

tasks:
  setup:
    desc: 開発環境をセットアップ
    cmds:
      - docker network create todo || true
      - aqua i
      - docker compose up -d

  migrate:
    desc: マイグレーションを実行
    deps:
      - setup
    cmds:
      - psqldef -U postgres -W password --host localhost -p 5432 todo < migration/schema.sql

  codegen:
    desc: コード生成
    deps:
      - migrate
    cmds:
      - uv run sqlacodegen --options use_inflect,nojoined postgresql://postgres:password@localhost:5432/todo --outfile src/infra/entity.py

  dev:
    desc: 開発サーバーを起動
    deps:
      - codegen
    cmds:
      - bash hack/run.sh uv run src/main.py
